url: https://lequieu.github.io
baseurl: /1cpn-model/
downloadurl: https://github.com/lequieu/1cpn-model
docurl: https://1cpn-model.readthedocs.io

# Site settings
title: 1CPN Model
email: your-email@domain.com
description: "The 1CPN Model of Chromatin. A multi-scale molecular model implemented in LAMMPS."



# Team names, titles and social links
people:
- name: Joshua Lequieu
  pic: lequieu
  position: Former Ph.D. @ U Chicago, currently UCSB

- name: Andres Cordoba
  pic: acordoba
  position: Former Post-Doc @ U Chicago, currently Universidad de Concepción

- name: Joshua Moller
  pic: moller
  position: Graduate Student @ U Chicago

- name: Juan de Pablo
  pic: dePablo
  position: Professor @ U Chicago



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title:
    url: 

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

# force include documentation
#include: 
#    - docs
#keep_files:
#    - docs/_static




